# -*- coding: utf-8 -*-
"""NaiveBayes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sSdC0ye3LvEp_8Fiiuxuyh2k1_FT1ndI
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/drive/MyDrive/Seminar/D.csv')
#print(df)

x = df.drop('class',axis=1)
y= df['class']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20,random_state=42)

print(x)
print(y)
model = GaussianNB()
model.fit(x_train, y_train)

y_pred = model.predict(x_test)
print(y_pred)

accuracy = accuracy_score(y_test, y_pred)*100
print(accuracy)